-- =====================================================================
-- Country list for the world map  (GENERATED - do not edit by hand)
-- Made by supabase/generate_seed_countries.py from:
--   map shapes : https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json
--   ISO codes  : https://cdn.jsdelivr.net/gh/lukes/ISO-3166-Countries-with-Regional-Codes@10.0/all/all.json
-- Run AFTER schema.sql (it needs the regions table to be filled).
--
-- 173 countries. Not included:
--   no ISO code on the map (stay grey): Kosovo, N. Cyprus, Somaliland
--   skipped: Antarctica
-- =====================================================================

insert into countries (country_code, name, map_id, region_id)
select v.country_code, v.name, v.map_id, r.region_id
from (values
    -- East Asia (16)
    ('BN', 'Brunei', '096', 'East Asia'),
    ('KH', 'Cambodia', '116', 'East Asia'),
    ('CN', 'China', '156', 'East Asia'),
    ('ID', 'Indonesia', '360', 'East Asia'),
    ('JP', 'Japan', '392', 'East Asia'),
    ('LA', 'Laos', '418', 'East Asia'),
    ('MY', 'Malaysia', '458', 'East Asia'),
    ('MN', 'Mongolia', '496', 'East Asia'),
    ('MM', 'Myanmar', '104', 'East Asia'),
    ('KP', 'North Korea', '408', 'East Asia'),
    ('PH', 'Philippines', '608', 'East Asia'),
    ('KR', 'South Korea', '410', 'East Asia'),
    ('TW', 'Taiwan', '158', 'East Asia'),
    ('TH', 'Thailand', '764', 'East Asia'),
    ('TL', 'Timor-Leste', '626', 'East Asia'),
    ('VN', 'Vietnam', '704', 'East Asia'),
    -- South Asia (12)
    ('AF', 'Afghanistan', '004', 'South Asia'),
    ('BD', 'Bangladesh', '050', 'South Asia'),
    ('BT', 'Bhutan', '064', 'South Asia'),
    ('IN', 'India', '356', 'South Asia'),
    ('KZ', 'Kazakhstan', '398', 'South Asia'),
    ('KG', 'Kyrgyzstan', '417', 'South Asia'),
    ('NP', 'Nepal', '524', 'South Asia'),
    ('PK', 'Pakistan', '586', 'South Asia'),
    ('LK', 'Sri Lanka', '144', 'South Asia'),
    ('TJ', 'Tajikistan', '762', 'South Asia'),
    ('TM', 'Turkmenistan', '795', 'South Asia'),
    ('UZ', 'Uzbekistan', '860', 'South Asia'),
    -- Middle East (19)
    ('AM', 'Armenia', '051', 'Middle East'),
    ('AZ', 'Azerbaijan', '031', 'Middle East'),
    ('CY', 'Cyprus', '196', 'Middle East'),
    ('EG', 'Egypt', '818', 'Middle East'),
    ('GE', 'Georgia', '268', 'Middle East'),
    ('IR', 'Iran', '364', 'Middle East'),
    ('IQ', 'Iraq', '368', 'Middle East'),
    ('IL', 'Israel', '376', 'Middle East'),
    ('JO', 'Jordan', '400', 'Middle East'),
    ('KW', 'Kuwait', '414', 'Middle East'),
    ('LB', 'Lebanon', '422', 'Middle East'),
    ('OM', 'Oman', '512', 'Middle East'),
    ('PS', 'Palestine', '275', 'Middle East'),
    ('QA', 'Qatar', '634', 'Middle East'),
    ('SA', 'Saudi Arabia', '682', 'Middle East'),
    ('SY', 'Syria', '760', 'Middle East'),
    ('TR', 'Turkey', '792', 'Middle East'),
    ('AE', 'United Arab Emirates', '784', 'Middle East'),
    ('YE', 'Yemen', '887', 'Middle East'),
    -- Europe (38)
    ('AL', 'Albania', '008', 'Europe'),
    ('AT', 'Austria', '040', 'Europe'),
    ('BY', 'Belarus', '112', 'Europe'),
    ('BE', 'Belgium', '056', 'Europe'),
    ('BA', 'Bosnia and Herz.', '070', 'Europe'),
    ('BG', 'Bulgaria', '100', 'Europe'),
    ('HR', 'Croatia', '191', 'Europe'),
    ('CZ', 'Czechia', '203', 'Europe'),
    ('DK', 'Denmark', '208', 'Europe'),
    ('EE', 'Estonia', '233', 'Europe'),
    ('FI', 'Finland', '246', 'Europe'),
    ('FR', 'France', '250', 'Europe'),
    ('DE', 'Germany', '276', 'Europe'),
    ('GR', 'Greece', '300', 'Europe'),
    ('HU', 'Hungary', '348', 'Europe'),
    ('IS', 'Iceland', '352', 'Europe'),
    ('IE', 'Ireland', '372', 'Europe'),
    ('IT', 'Italy', '380', 'Europe'),
    ('LV', 'Latvia', '428', 'Europe'),
    ('LT', 'Lithuania', '440', 'Europe'),
    ('LU', 'Luxembourg', '442', 'Europe'),
    ('MK', 'Macedonia', '807', 'Europe'),
    ('MD', 'Moldova', '498', 'Europe'),
    ('ME', 'Montenegro', '499', 'Europe'),
    ('NL', 'Netherlands', '528', 'Europe'),
    ('NO', 'Norway', '578', 'Europe'),
    ('PL', 'Poland', '616', 'Europe'),
    ('PT', 'Portugal', '620', 'Europe'),
    ('RO', 'Romania', '642', 'Europe'),
    ('RU', 'Russia', '643', 'Europe'),
    ('RS', 'Serbia', '688', 'Europe'),
    ('SK', 'Slovakia', '703', 'Europe'),
    ('SI', 'Slovenia', '705', 'Europe'),
    ('ES', 'Spain', '724', 'Europe'),
    ('SE', 'Sweden', '752', 'Europe'),
    ('CH', 'Switzerland', '756', 'Europe'),
    ('UA', 'Ukraine', '804', 'Europe'),
    ('GB', 'United Kingdom', '826', 'Europe'),
    -- North America (4)
    ('CA', 'Canada', '124', 'North America'),
    ('GL', 'Greenland', '304', 'North America'),
    ('MX', 'Mexico', '484', 'North America'),
    ('US', 'United States of America', '840', 'North America'),
    -- Latin America (27)
    ('AR', 'Argentina', '032', 'Latin America'),
    ('BS', 'Bahamas', '044', 'Latin America'),
    ('BZ', 'Belize', '084', 'Latin America'),
    ('BO', 'Bolivia', '068', 'Latin America'),
    ('BR', 'Brazil', '076', 'Latin America'),
    ('CL', 'Chile', '152', 'Latin America'),
    ('CO', 'Colombia', '170', 'Latin America'),
    ('CR', 'Costa Rica', '188', 'Latin America'),
    ('CU', 'Cuba', '192', 'Latin America'),
    ('DO', 'Dominican Rep.', '214', 'Latin America'),
    ('EC', 'Ecuador', '218', 'Latin America'),
    ('SV', 'El Salvador', '222', 'Latin America'),
    ('FK', 'Falkland Is.', '238', 'Latin America'),
    ('GT', 'Guatemala', '320', 'Latin America'),
    ('GY', 'Guyana', '328', 'Latin America'),
    ('HT', 'Haiti', '332', 'Latin America'),
    ('HN', 'Honduras', '340', 'Latin America'),
    ('JM', 'Jamaica', '388', 'Latin America'),
    ('NI', 'Nicaragua', '558', 'Latin America'),
    ('PA', 'Panama', '591', 'Latin America'),
    ('PY', 'Paraguay', '600', 'Latin America'),
    ('PE', 'Peru', '604', 'Latin America'),
    ('PR', 'Puerto Rico', '630', 'Latin America'),
    ('SR', 'Suriname', '740', 'Latin America'),
    ('TT', 'Trinidad and Tobago', '780', 'Latin America'),
    ('UY', 'Uruguay', '858', 'Latin America'),
    ('VE', 'Venezuela', '862', 'Latin America'),
    -- Africa & Oceania (57)
    ('DZ', 'Algeria', '012', 'Africa & Oceania'),
    ('AO', 'Angola', '024', 'Africa & Oceania'),
    ('AU', 'Australia', '036', 'Africa & Oceania'),
    ('BJ', 'Benin', '204', 'Africa & Oceania'),
    ('BW', 'Botswana', '072', 'Africa & Oceania'),
    ('BF', 'Burkina Faso', '854', 'Africa & Oceania'),
    ('BI', 'Burundi', '108', 'Africa & Oceania'),
    ('CM', 'Cameroon', '120', 'Africa & Oceania'),
    ('CF', 'Central African Rep.', '140', 'Africa & Oceania'),
    ('TD', 'Chad', '148', 'Africa & Oceania'),
    ('CG', 'Congo', '178', 'Africa & Oceania'),
    ('CI', 'Côte d''Ivoire', '384', 'Africa & Oceania'),
    ('CD', 'Dem. Rep. Congo', '180', 'Africa & Oceania'),
    ('DJ', 'Djibouti', '262', 'Africa & Oceania'),
    ('GQ', 'Eq. Guinea', '226', 'Africa & Oceania'),
    ('ER', 'Eritrea', '232', 'Africa & Oceania'),
    ('ET', 'Ethiopia', '231', 'Africa & Oceania'),
    ('FJ', 'Fiji', '242', 'Africa & Oceania'),
    ('TF', 'Fr. S. Antarctic Lands', '260', 'Africa & Oceania'),
    ('GA', 'Gabon', '266', 'Africa & Oceania'),
    ('GM', 'Gambia', '270', 'Africa & Oceania'),
    ('GH', 'Ghana', '288', 'Africa & Oceania'),
    ('GN', 'Guinea', '324', 'Africa & Oceania'),
    ('GW', 'Guinea-Bissau', '624', 'Africa & Oceania'),
    ('KE', 'Kenya', '404', 'Africa & Oceania'),
    ('LS', 'Lesotho', '426', 'Africa & Oceania'),
    ('LR', 'Liberia', '430', 'Africa & Oceania'),
    ('LY', 'Libya', '434', 'Africa & Oceania'),
    ('MG', 'Madagascar', '450', 'Africa & Oceania'),
    ('MW', 'Malawi', '454', 'Africa & Oceania'),
    ('ML', 'Mali', '466', 'Africa & Oceania'),
    ('MR', 'Mauritania', '478', 'Africa & Oceania'),
    ('MA', 'Morocco', '504', 'Africa & Oceania'),
    ('MZ', 'Mozambique', '508', 'Africa & Oceania'),
    ('NA', 'Namibia', '516', 'Africa & Oceania'),
    ('NC', 'New Caledonia', '540', 'Africa & Oceania'),
    ('NZ', 'New Zealand', '554', 'Africa & Oceania'),
    ('NE', 'Niger', '562', 'Africa & Oceania'),
    ('NG', 'Nigeria', '566', 'Africa & Oceania'),
    ('PG', 'Papua New Guinea', '598', 'Africa & Oceania'),
    ('RW', 'Rwanda', '646', 'Africa & Oceania'),
    ('SS', 'S. Sudan', '728', 'Africa & Oceania'),
    ('SN', 'Senegal', '686', 'Africa & Oceania'),
    ('SL', 'Sierra Leone', '694', 'Africa & Oceania'),
    ('SB', 'Solomon Is.', '090', 'Africa & Oceania'),
    ('SO', 'Somalia', '706', 'Africa & Oceania'),
    ('ZA', 'South Africa', '710', 'Africa & Oceania'),
    ('SD', 'Sudan', '729', 'Africa & Oceania'),
    ('TZ', 'Tanzania', '834', 'Africa & Oceania'),
    ('TG', 'Togo', '768', 'Africa & Oceania'),
    ('TN', 'Tunisia', '788', 'Africa & Oceania'),
    ('UG', 'Uganda', '800', 'Africa & Oceania'),
    ('VU', 'Vanuatu', '548', 'Africa & Oceania'),
    ('EH', 'W. Sahara', '732', 'Africa & Oceania'),
    ('ZM', 'Zambia', '894', 'Africa & Oceania'),
    ('ZW', 'Zimbabwe', '716', 'Africa & Oceania'),
    ('SZ', 'eSwatini', '748', 'Africa & Oceania')
) as v (country_code, name, map_id, region_name)
join regions r on r.name = v.region_name;

-- Check: the join above silently drops a row whose region name has no match,
-- so this should return 173:
--   select count(*) from countries;
