"""
Writes web/config.js from the values in .env.

    python -m pipeline.make_web_config

The dashboard is a plain web page, so it needs the Supabase address and a key
inside a file the browser can read. That key must be the PUBLISHABLE one
(sb_publishable_... or the legacy "anon" key): it can only READ, because of the
Row Level Security rules in schema.sql.

This script refuses to write a secret key, so a mistake can't publish one.
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

from pipeline import config

load_dotenv()

OUTPUT = Path(__file__).resolve().parent.parent / "web" / "config.js"


def main():
    url = config.SUPABASE_URL
    key = os.getenv("SUPABASE_PUBLISHABLE_KEY", "").strip()

    if not url:
        print("SUPABASE_URL is missing from .env")
        return 1
    if not key:
        print("SUPABASE_PUBLISHABLE_KEY is missing from .env.")
        print("Supabase -> Project Settings -> API Keys -> Publishable key (sb_publishable_...)")
        return 1

    # Safety check: never put a writing key into a public web file.
    if key.startswith("sb_secret_") or "service_role" in key:
        print("That looks like a SECRET key. Use the publishable (read-only) key instead.")
        print("Nothing was written.")
        return 1

    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(
        "/* Generated by: python -m pipeline.make_web_config  —  do not edit by hand.\n"
        "   This key is the PUBLIC read-only key; Row Level Security blocks all writes. */\n"
        "window.SUPABASE = {\n"
        f'  url: "{url}",\n'
        f'  key: "{key}",\n'
        "};\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    print(f"  url: {url}")
    print(f"  key: {key[:12]}… ({len(key)} characters, read-only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
