/* Generated by: python -m pipeline.make_web_config  —  do not edit by hand.
   This key is the PUBLIC read-only key; Row Level Security blocks all writes. */
window.SUPABASE = {
  url: "https://exzdoaxhaixakznylxmx.supabase.co",
  key: "sb_publishable_ZEMPZRhfjbfQBes_0FUxfw_svg0eg7V",
};
